#:kivy 2.3.0
<BackgroundBox>:
    Image:
        canvas.after:
            Color:
                rgba: 0, 0, 0, 0.7   # black with 50% opacity
            Rectangle:
                pos: self.pos
                size: self.size
        source: root.bg_image
        allow_stretch: False
        keep_ratio: True
        size_hint: None, None
        size: self.texture_size
        pos: ((self.parent.width - self.width) / 2, (self.parent.height - self.height) / 2)



