#:kivy 2.3.0
<ContentArea>:
    BoxLayout: # how can i create a component that can conditionally display content dynamically i.e dictated from the outside
        orientation:"vertical" 
        BoxLayout: # default content
            orientation: "vertical"
            opacity: 1 if root.control_display == "" else 0
            size_hint_y: 1 if root.control_display == "" else 0
            height: self.parent.height if root.control_display == "" else 0
            BoxLayout: # status info
                orientation: "vertical"
                Widget:
                    height: 100
                CircleImage:
                    size_hint: None, None
                    size: 100, 100
                    pos_hint: {"center_x": 0.5, "center_y":0.5}
                Label:
                    id:"name"
                    text: "Name: " + app.name
                Label:
                    id:"xp"
                    text: "XP: "+ str(app.xp) 
                Label:
                    id:"level"
                    text: "Level: "+ str(app.level)
                Label:
                    id:"growth_rate"
                    text: "Growth Rate: "+ str(app.xp_rate) + " xp/day"
                Label:
                    id:"titles"
                    text: "Titles:"+ app.get_titles()
            BoxLayout: # control action
                FloatLayout:
                    pos: self.parent.pos
                    size: self.parent.size
                    FloatLayout: # portrait/mobile layout
                        opacity: 1 if root.width <= 800 else 0
                        IconButton:
                            size_hint: None, None
                            size: 50, 50
                            pos: self.parent.width - 100 , 50
                            on_press: root.set_control_display("acc")
                        IconButton:
                            size_hint: None, None
                            size: 40, 40
                            pos: (self.parent.width - 100) - 180 , 50
                        IconButton:
                            size_hint: None, None
                            size: 40, 40
                            pos: (self.parent.width - 100) - 90 , 50
                        IconButton:
                            size_hint: None, None
                            size: 40, 40
                            pos: self.parent.width - 100 - 40 , 140
                        IconButton:
                            size_hint: None, None
                            size: 40, 40
                            pos: self.parent.width - 60 , 170

                    FloatLayout: #landscape / pc layout
                        pos: self.parent.pos
                        size: self.parent.size
                        opacity: 1 if root.width > 800 else 0
                        BoxLayout:
                            orientation:"horizontal"
                            size_hint: None, None
                            size: 500,40
                            x: (self.parent.width/2) - (self.width/2) + root.offset
                            y: self.parent.y + self.height
                            IconButton:
                                size_hint: None, None
                                size: 40, 40
                            Widget:
                            IconButton:
                                size_hint: None, None
                                size: 40, 40
                            Widget:
                            IconButton:
                                size_hint: None, None
                                size: 40, 40
        BoxLayout:  # conditional content
            size_hint_y: 1 if root.control_display != "" else 0
            height: self.parent.height if root.control_display != "" else 0
            opacity: 1 if root.control_display != "" else 0
            canvas.before:
                Color:
                    rgba: 1,1,0,1
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "lets go"
                size_hint_y: 1   # fills parent BoxLayout
                text_size: self.width, None
                valign: 'middle'
                halign: 'center'