#:kivy 2.3.0
<CreatePlayerForm>:
    orientation: "vertical"
    Widget:
    Label:
        text: "Player Name"
        size_hint_y: None
        height: 20
        font_size: "16sp"
        bold: True
        color: 1, 1, 1, 1   # RGBA (white)
        halign: "center"
        valign: "middle"
        text_size: self.size
    Widget:
        size_hint_y: None
        height: 20
    Widget:
        size_hint: None, None
        size: 300, 40
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        canvas.before:
            Color:
                rgba: 0.15, 0.15, 0.1, 0.5
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [10]
        TextInput:
            id: name
            size: self.parent.size
            pos: self.parent.pos
            font_size: 16
            background_normal: ""
            background_active: ""
            background_color: 0, 0, 0, 0
            foreground_color: 1, 1, 1, 1
            cursor_color: 1, 1, 1, 1
            padding: [10,10]
            multiline: False
    Widget:
        size_hint_y: None
        height: 20
    Button:
        text:"submit"
        on_press: root.submit_form()
        size_hint: None, None
        height: 40
        width: 300
        font_size: 16
        color: 1, 1, 1, 1
        background_normal: "src/assets/bg_btn.jpg"
        background_down: ""
        border: (16, 16, 16, 16)  # left, right, top, bottom pixels
        pos_hint:{"center_x": 0.5, "center_y": 0.5}
    Widget:

