#:kivy 2.3.0
<MidGroundFloat>:
    size: self.parent.size
    pos: self.parent.pos
    BoxLayout: # body
        pos: root.pos
        size: root.size
        orientation: "vertical"
        Nav:
            control: root.set_current_content
        
        ScreenManager:
            id: sm
            Screen:
                name: "stats"
                StatsContentArea:
                    create_form: False
                    content: root.local_list
                    offset: root.offset
            Screen:
                name: "reports"
                ReportsContentArea:
                    content: root.local_list
                    offset: root.offset
                    visible: True
            Screen:
                name: "attributes"
                AttributesContentArea:
                    content: root.local_list
                    offset: root.offset
                    visible: True
            Screen:
                name: "professions"
                ProfessionsContentArea:
                    content: root.local_list
                    offset: root.offset
                    visible: True
            Screen:
                name: "settings"
                SettingsContentArea:
                    content: root.local_list
                    offset: root.offset
                    visible: root.current_content  == "settings"
                    canvas.before:
                        Color:
                            rgba: 1,0,0,1
                        Rectangle:
                            pos: self.pos
                            size: self.size