#:kivy 2.3.0
#:import NoTransition kivy.uix.screenmanager.NoTransition
<MissionCenter>:
    orientation: "vertical"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation: "horizontal"
            padding:[20]
            size_hint_y: None
            height: 80
            canvas.before:
                Color:
                    rgba: 0,0,0,0.2
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]
            Widget:
            TextInput:
                on_text: root.search(self.text)
                pos_hint: {"center_y":0.5}
                font_size: 16
                background_normal: ""
                background_active: ""
                background_color: 1, 1, 1, 0.2
                foreground_color: 1, 1, 1, 1
                cursor_color: 1, 1, 1, 1
                padding: [10,10]
                multiline: False
            Widget:
            # change the bellow to an icon button
            IconButton:
                on_press: root.add_form = not root.add_form
                image_path: "src/assets/add_mission.png" if not root.add_form else "src/assets/list.png"
                size_hint: None, None
                base_width: 250 if not root.add_form else 230
                base_height: 60
                hover_enabled: False


            Widget:
        ScreenManager:
            id: sm
            transition: NoTransition()
            Screen:
                name: "list"
                ScrollableList:
                    id: list
                    items: root.missions
                    control: root.delete
            # control: root.mission_control
            Screen:
                name: "form"
                BoxLayout:
                    orientation: "vertical"
                    canvas.before:
                        Color:
                            rgba: 0,0,0,0.2
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [20]
                    Widget:
                    BoxLayout:
                        orientation:"horizontal"
                        padding: 20
                        size_hint: 0.7, None
                        height: 80
                        pos_hint: {"center_x": 0.5}
                        Label:
                            text: "name *"
                            size_hint_x: None
                            width: max(self.texture_size[0] + dp(20), dp(120))
                            text_size: None, None
                        TextInput:
                            on_text: root.form_name = self.text
                            id: name
                            font_size: 16
                            background_normal: ""
                            background_active: ""
                            background_color: 1, 1, 1, 0.2
                            foreground_color: 1, 1, 1, 1
                            cursor_color: 1, 1, 1, 1
                            padding: [10,10]
                            multiline: False
                    Widget:
                    BoxLayout:
                        orientation:"horizontal"
                        padding: 20
                        size_hint: 0.7, None
                        height: 80
                        pos_hint: {"center_x": 0.5}
                        Label:
                            text: "description"
                            size_hint_x: None
                            width: max(self.texture_size[0] + dp(20), dp(120))
                            text_size: None, None
                        TextInput:
                            on_text: root.form_description = self.text
                            id: description
                            font_size: 16
                            background_normal: ""
                            background_active: ""
                            background_color: 1, 1, 1, 0.2
                            foreground_color: 1, 1, 1, 1
                            cursor_color: 1, 1, 1, 1
                            padding: [10,10]
                            multiline: False
                    Widget:
                    BoxLayout:
                        orientation:"horizontal"
                        padding: 20
                        size_hint: 0.7, None
                        height: 80
                        pos_hint: {"center_x": 0.5}
                        Label:
                            text: "difficulty"
                            size_hint_x: None
                            width: max(self.texture_size[0] + dp(20), dp(120))
                            text_size: None, None
                        Slider:
                            id: difficulty
                            min: 0
                            max: 10
                            value: 5
                            step: 1
                            on_value: root.form_difficulty = self.value
                    Widget:
                    BoxLayout:
                        orientation:"horizontal"
                        padding: 20
                        size_hint: 0.7, None
                        height: 80
                        pos_hint: {"center_x": 0.5}
                        Label:
                            text: "deadline"
                            size_hint_x: None
                            width: max(self.texture_size[0] + dp(20), dp(120))
                            text_size: None, None
                        BoxLayout:
                            spacing: 10

                            Spinner:
                                text: "Year"
                                values: [str(y) for y in range(2020, 2031)]
                                background_normal: "src/assets/spinner.png"
                                background_down: "src/assets/spinner.png"
                                border: 0, 0, 0, 0
                                background_color: 1, 1, 1, 1
                                id: year
                            Spinner:
                                text: "Month"
                                values: [str(m) for m in range(1, 13)]
                                background_normal: "src/assets/spinner.png"
                                background_down: "src/assets/spinner.png"
                                border: 0, 0, 0, 0
                                background_color: 1, 1, 1, 1
                                id: month
                            Spinner:
                                text: "Day"
                                values: [str(d) for d in range(1, 32)]
                                background_normal: "src/assets/spinner.png"
                                background_down: "src/assets/spinner.png"
                                border: 0, 0, 0, 0
                                background_color: 1, 1, 1, 1
                                id: day
                    Widget:
                    BoxLayout:
                        Widget:
                        IconButton:
                            image_path: "src/assets/submit.png"
                            base_height: 80
                            base_width: 300
                            size_hint_x: None
                            width:300
                            on_press: root.submit()
                        Widget:
                    # Button:
                    #     text:"submit"
                    #     size_hint_y: None
                    #     height: 80
                    #     on_press: root.submit()
                    #     background_normal: "src/assets/grid2.jpg"
                    #     background_active: "src/assets/grid4.jpg"


