#:kivy 2.3.0
<Nav>:
    orientation: "horizontal"
    size_hint_y: None
    height: 50
    IconButton:
        size_hint: None, None
        size: 50, 50
    Widget:
    BoxLayout:
        orientation: "horizontal"
        IconButton:
            size_hint: None, None
            size: 40, 40
        Widget:
        IconButton:
            size_hint: None, None
            size: 40, 40
        Widget:
        IconButton:
            size_hint: None, None
            size: 40, 40

