#:kivy 2.3.0
<ProfessionsContentArea>:
    BoxLayout: # default content
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: 1,1,1,0.9
            RoundedRectangle:
                source: "src/assets/grid-i.png"
                pos: self.pos
                size: self.size
                radius:[20]
        Scatter:    
            id: scatter
            size: self.parent.size
            size_hint: 1, 1
            do_rotation: False
            do_translation: True
            do_scale: True
            scale_min: 0.5
            scale_max: 3

            BoxLayout:
                id: world
                size_hint: None, None
                size: root.width-100, root.height-100
                pos: (scatter.width - self.width)/2, (scatter.height - self.height)/2
                orientation: "vertical"
                canvas.before:
                    # Set the color of the outline (RGBA format)
                    Color:
                        rgba: 0, 0.5, 1, 1  # Red color with full opacity
                    # Draw the rectangle outline
                    Line:
                        rectangle: (self.x, self.y, self.width, self.height)  # Outline around the box
                        width: 3  # Thickness of the outline
                ProfessionList:
                    professions: root.professions
                    visible: True