#:kivy 2.3.0
#:import NoTransition kivy.uix.screenmanager.NoTransition
<StatsContentArea>:
    BoxLayout:
        id: container
        orientation:"vertical" 
        BoxLayout: # default content
            orientation: "vertical"
            opacity: 1 if root.control_display == "" else 0
            size_hint_y: 1 if root.control_display == "" else 0
            height: self.parent.height if root.control_display == "" else 0

            BoxLayout: # status info
                orientation: "vertical"
                padding:[10, 100]
                size_hint: None, None
                width: 450
                height: 600
                pos_hint: {"center_x":0.5, "center_y": 0.5}
                canvas.before:
                    Color:
                        rgba: 1,1,1,0.9
                    RoundedRectangle:
                        source: "src/assets/status-window.png"
                        pos: self.pos
                        size: self.size
                        radius:[20]
                Widget:
                    height: 100
                CircleImage:
                    image_path:"src/assets/eli.jpg"
                    size_hint: None, None
                    size: 100, 100
                    pos_hint: {"center_x": 0.5, "center_y":0.5}
                Widget:
                    height: 100
                Label:
                    id: name
                    markup: True
                    font_size:30
                    text: "[b][color=#00CBD7]{}[/color][/b]".format(app.profile.name if app.profile else "")
                    # text: f"[b][color=#00CBD7]{"" if not app.profile else app.profile.name}[/color][/b]"
                Label:
                    id:"xp"
                    markup: True
                    text: "[b][color=#00CBD7]XP : [/color][/b]"+ f"[b][color=#00f123]{str(0 if not app.profile else app.profile.xp)}[/color][/b]" 
                Label:
                    id:"level"
                    markup: True
                    text: "[b][color=#00CBD7]Level : [/color][/b]"+ f"[b][color=#00f123]{str(0 if not app.profile else app.profile.level)}[/color][/b]" 
                Label:
                    id:"growth_rate"
                    markup: True
                    text: "[b][color=#00CBD7]Growth Rate : [/color][/b]"+ f"[b][color=#00f123]{str(0 if not app.profile else app.profile.xp_rate)} xp/day[/color][/b]"
                Label:
                    markup: True
                    font_size:25
                    text: "[b][color=#00CBD7]Titles [/color][/b]"
                Label:
                    id:"titles"
                    markup: True
                    text: f"[b][color=#00f123]{app.get_titles()}[/color][/b]"

            ScreenManager:
                id: controls_sm
                transition: NoTransition()
                size_hint_y: None
                height: 200
                Screen:
                    name: "mobile"
                    BoxLayout:
                        FloatLayout: # portrait/mobile layout
                            opacity: 1 if not root.is_desktop else 0
                            size_hint_y: None
                            height: self.parent.height if not root.is_desktop else 0
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/report2.png"
                                size_hint: None, None
                                size: 50, 50
                                pos: self.parent.width - 100 , 50
                                on_press: root.set_control_display("report")
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/settings.png"
                                size_hint: None, None
                                size: 40, 40
                                pos: (self.parent.width - 100) - 180 , 50
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/settings.png"  
                                size_hint: None, None
                                size: 40, 40
                                pos: (self.parent.width - 100) - 90 , 50
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/activity.png"
                                size_hint: None, None
                                size: 40, 40
                                pos: self.parent.width - 100 - 40 , 140
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/mission.png"
                                size_hint: None, None
                                size: 40, 40
                                pos: self.parent.width - 60 , 170
                                on_press: root.set_control_display("mission")

                Screen:
                    name: "desktop"
                    BoxLayout:#landscape / pc layout
                        orientation:"vertical"
                        Widget:
                        BoxLayout:
                            orientation:"horizontal"
                            size_hint: None, None
                            size: 500,40
                            pos_hint: {"center_x": 0.5}
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/mission-i.png"
                                size_hint: None, None
                                base_height: 40
                                base_width:120
                                on_press: root.set_control_display("mission") #REPORT
                            Widget:
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/activity-i.png"
                                size_hint: None, None
                                base_height: 40
                                base_width:120
                                on_press: root.set_control_display("compound_activity")
                            Widget:
                            IconButton:
                                hover_enabled: False
                                image_path: "src/assets/report2-i.png"
                                size_hint: None, None
                                base_height: 45
                                base_width:150
                                on_press: root.set_control_display("report")
        
        BoxLayout:  # conditional content - mission
            id: mission
            orientation: "vertical"
            size_hint_y: 1 if root.control_display == "mission" else 0
            height: self.parent.height if root.control_display == "mission" else 0
            opacity: 1 if root.control_display == "mission" else 0
            padding: 24
            canvas.before:
                Color:
                    rgba: 0,0,0,0.8
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]
            BoxLayout:
                orientation:"horizontal"
                size_hint_y: None
                height: 30
                padding: [0,0,0,12]
                Widget:
                    size_hint_x: None
                    width: 50
                IconButton:
                    on_press: root.set_control_display("")
                    image_path: "src/assets/back-i.png"
                    size_hint: None, None
                    # size: 20, 20
                    base_width: 30
                    base_height: 30
                    hover_enabled: False
                Widget:

        BoxLayout:  # conditional content - compound activity
            id: compound_activity
            orientation: "vertical"
            size_hint_y: 1 if root.control_display == "compound_activity" else 0
            height: self.parent.height if root.control_display == "compound_activity" else 0
            opacity: 1 if root.control_display == "compound_activity" else 0
            padding: 24
            canvas.before:
                Color:
                    rgba: 0,0,0,0.8
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]
            BoxLayout:
                orientation:"horizontal"
                size_hint_y: None
                height: 30
                padding: [0,0,0,12]
                Widget:
                    size_hint_x: None
                    width: 50
                IconButton:
                    on_press: root.set_control_display("")
                    image_path: "src/assets/back-i.png"
                    size_hint: None, None
                    # size: 20, 20
                    base_width: 30
                    base_height: 30
                    hover_enabled: False
                Widget:
        BoxLayout:  # conditional content - report
            id: report
            orientation: "vertical"
            size_hint_y: 1 if root.control_display == "report" else 0
            height: self.parent.height if root.control_display == "report" else 0
            opacity: 1 if root.control_display == "report" else 0
            padding: 24
            canvas.before:
                Color:
                    rgba: 0,0,0,0.8
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]
            BoxLayout:
                orientation:"horizontal"
                size_hint_y: None
                height: 30
                padding: [0,0,0,12]
                Widget:
                    size_hint_x: None
                    width: 50
                IconButton:
                    on_press: root.set_control_display("")
                    image_path: "src/assets/back-i.png"
                    size_hint: None, None
                    # size: 20, 20
                    base_width: 30
                    base_height: 30
                    hover_enabled: False
                Widget:
            