#:kivy 2.3.0
<HomeScreen>:
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"
        BoxLayout:
            font_name: "src/assets/main.ttf"
            orientation:"vertical"
            size_hint: None, None
            size: root.width - root.custom_padding*2, root.height - root.custom_padding*2
            FloatLayout:
                BackgroundVideo:
                    overlay_opacity: 0.4
                    video_path: "src/assets/14770388_1920_1080_24fps.mp4"
                    size_hint: None,None
                    size: root.width, root.height
                    pos: root.pos
                MidGroundFloat:
                    offset: root.custom_padding
