#:kivy 2.3.0
<HomeScreen>:
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"
        BoxLayout:
            orientation:"vertical"
            size_hint: None, None
            size: root.width - root.custom_padding*2, root.height - root.custom_padding*2
            FloatLayout:
                BackgroundBox:
                MidGroundFloat:
                    offset: root.custom_padding
