#:kivy 2.3.0
<SetupScreen>:
    FloatLayout:
        BackgroundVideo:
            overlay_opacity: 0.5
            video_path: "src/assets/12900822_1920_1080_30fps.mp4"
        AnchorLayout:
            anchor_x:"center"
            anchor_y: "center"
            CreatePlayerForm:
                id:form
                size_hint: None, None
                size: root.width - 100, root.height -100