BEGIN TRANSACTION;

INSERT INTO compound_activities (name, xp, tags, custom, hidden) VALUES
('Rise Early',1700,'["daily"]',FALSE,FALSE),
('Pray',1700,'["daily"]',FALSE,FALSE),
('Technical Practice',1700,'["daily"]',FALSE,FALSE),
('Workout',2500,'["daily"]',FALSE,FALSE),
('Meditate',1700,'["daily"]',FALSE,FALSE),
('Plan the Day',1700,'["daily"]',FALSE,FALSE),
('Prepare Meals',1700,'["daily"]',FALSE,FALSE),
('Dress Well',1700,'["daily"]',FALSE,FALSE),
('Quality Work (Morning)',1700,'["daily"]',FALSE,FALSE),
('Speech Practice (Morning)',1700,'["daily"]',FALSE,FALSE),
('Stress Control (Morning)',1700,'["daily"]',FALSE,FALSE),
('Thought Discipline (Morning)',1700,'["daily"]',FALSE,FALSE),
('Money Research (Morning)',1700,'["daily"]',FALSE,FALSE),
('Work on Personal Projects (Morning)',1700,'["daily"]',FALSE,FALSE),
('Eat Lunch',1700,'["daily"]',FALSE,FALSE),
('Quality Work (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Speech Practice (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Stress Control (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Thought Discipline (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Money Research (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Work on Personal Projects (Afternoon)',1700,'["daily"]',FALSE,FALSE),
('Bureaucratic Task',50000,'["discomfort"]',FALSE,FALSE),
('Maintain Relationships',10000,'["discomfort"]',FALSE,FALSE),
('Demonetization Work',50000,'["discomfort"]',FALSE,FALSE),
('Confront Someone',10000,'["discomfort"]',FALSE,FALSE),
('Control Flooding',10000,'["discomfort"]',FALSE,FALSE),
('Execute XSWAG',1000,'["generic"]',FALSE,FALSE),
('Study',2000,'["generic"]',FALSE,FALSE),
('Take Notes',1000,'["generic"]',FALSE,FALSE),
('Use Deductive Skill',1000,'["generic"]',FALSE,FALSE),
('Use Deductive Skill (Normal)',2000,'["generic"]',FALSE,FALSE),
('Use Personal Gift',3000,'["generic"]',FALSE,FALSE),
('Design Something',1000,'["generic"]',FALSE,FALSE),
('Solve Problem',1000,'["generic"]',FALSE,FALSE),
('Create Plan',1000,'["generic"]',FALSE,FALSE),
('Organize Things',1000,'["generic"]',FALSE,FALSE),
('Manage People',1000,'["generic"]',FALSE,FALSE),
('Delegate Task',1000,'["generic"]',FALSE,FALSE),
('Win Debate',2000,'["generic"]',FALSE,FALSE),
('1-on-1 Conversation',1000,'["generic"]',FALSE,FALSE),
('Group Conversation',2000,'["generic"]',FALSE,FALSE),
('Give Presentation',3000,'["generic"]',FALSE,FALSE),
('Technical Hand Work',1000,'["generic"]',FALSE,FALSE),
('Document Work',1000,'["generic"]',FALSE,FALSE),
('Mini Project Work',3000,'["generic"]',FALSE,FALSE),
('Major Project Work',5000,'["generic"]',FALSE,FALSE),
('Complete Compound Task',1000,'["generic"]',FALSE,FALSE),
('Research',1000,'["generic"]',FALSE,FALSE),
('Act with Values',1000,'["generic"]',FALSE,FALSE),
('Improve Image',1000,'["generic"]',FALSE,FALSE),
('Maintain Good Posture',1000,'["generic"]',FALSE,FALSE),
('Maintain Good Demeanor',1000,'["generic"]',FALSE,FALSE),
('Use Time Well',1000,'["generic"]',FALSE,FALSE),
('Use Energy Efficiently',1000,'["generic"]',FALSE,FALSE),
('Wash Clothes',1000,'["generic"]',FALSE,FALSE),
('Emotional Flooding',-10000,'["negative"]',FALSE,FALSE),
('Act Against Values',-10000,'["negative"]',FALSE,FALSE),
('Break SWAG Rule',-2000,'["negative"]',FALSE,FALSE),
('Be Lazy',-5000,'["negative"]',FALSE,FALSE),
('Binge Entertainment',-5000,'["negative"]',FALSE,FALSE),
('Skip Workout',-5000,'["negative"]',FALSE,FALSE);

COMMIT;